### ISSUE TITLE
Add Oj dependency

### ISSUE THREAD

**Issue by nesaulov** [nesaulov/surrealist#69]
I am going to add [Oj](https://github.com/ohler55/oj) dependency. It's not that good to have a dependency, but on the other hand Oj is 2.5x faster than stdlib JSON.
```
Comparison:
                  oj:   265888.1 i/s
           multi_json:   176083.1 i/s - 1.51x  slower
                json:   100783.9 i/s - 2.64x  slower
```
